POST Data API
CloudClub-uoft/iot-device pull request #22
Opened 2021-06-26 01:54 UTC by Lepabryce

Created a route for posting data using `findOne` to check that a sent API key exists from a Device in the db.  If successful, a new document using the temporary Data model is created in the db using `findOneAndUpdate`. Testing using mocha is also implemented. 

A deprecation warning is logged in the terminal when the route is called, but according to the [documentation](https://mongoosejs.com/docs/deprecations.html#findandmodify), this warning can be ignored. Not sure if this is something to worry about.

Closes #16

2021-06-28 00:35 UTC, harsimrat99 requested changes
Hi @Lepabryce ,

Thanks for making this API update. I would like to clarify something before we proceed with merging this pull request. Regarding the **findOneAndUpdate** function:

Does executing this function remove previously stored data? For example, if {temp: 12.3} was stored for a specific device, then does calling this function with the new data, say {temp: 16.4} replace the previous value?

If this is the case, then the previous data must be preserved. However, if this function adds new data without removing previous data then it is considered to be safe. Please let me know about this.

P.S. I have added some resources to the data modelling [issue ](https://github.com/CloudClub-uoft/iot-device-backend/issues/14 )and they may prove helpful.

2021-06-28 19:51 UTC, Lepabryce commented
Hey @harsimrat99,

You're correct, findOneAndUpdate would overwrite data. I've now changed it to create a new document each time this is called.

2021-06-30 23:43 UTC, JLefebvre55 commented
@harsimrat99 re-requested review

2021-07-02 23:24 UTC, harsimrat99 approved these changes

2021-07-02 23:25 UTC, merged